# Generated by Django 3.0.3 on 2020-02-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20200220_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='min_bal',
            field=models.IntegerField(default=2000),
        ),
    ]
