# Generated by Django 3.0.3 on 2020-02-20 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_auto_20200220_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='min_bal',
            new_name='balance',
        ),
    ]
