# Generated by Django 3.0.3 on 2020-02-20 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_auto_20200220_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(2000)]),
        ),
    ]
