# Generated by Django 3.0.3 on 2020-02-23 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_auto_20200223_0625'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
