# Generated by Django 3.0.3 on 2020-02-23 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_delete_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciver_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciver_acc', to='userapp.Account')),
                ('sender_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_acc', to='userapp.Account')),
            ],
        ),
    ]
