# Generated by Django 3.0.3 on 2020-02-23 07:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='reciver_acc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_reciver', to='userapp.Account'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='sender_acc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_sender', to='userapp.Account'),
        ),
    ]
