# Generated by Django 3.0.3 on 2020-02-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_transactions_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='action',
            field=models.BooleanField(default=True),
        ),
    ]
