# Generated by Django 3.0.3 on 2020-02-24 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_auto_20200223_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='action',
        ),
    ]
